name: numberpicker
version: 2.1.2
description: NumberPicker is a widget allowing user to choose numbers by scrolling spinners.
homepage: https://github.com/MarcinusX/NumberPicker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  infinite_listview: ^1.1.0

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter