name: numberpicker
version: 0.1.7
description: NumberPicker is a widget allowing user to choose numbers by scrolling spinners.
author: Marcin Szalek <marcinszalek1@gmail.com>
homepage: https://github.com/MarcinusX/NumberPicker

environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter