name: numberpicker
version: 1.1.0
description: NumberPicker is a widget allowing user to choose numbers by scrolling spinners.
authors:
  - Marcin Szalek <marcinszalek1@gmail.com>
  - Monika Stobieniecka <mstobieniecka1@gmail.com>
homepage: https://github.com/MarcinusX/NumberPicker

environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  infinite_listview: ^1.0.0

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter